export const mappedNameList = {
  organization: "소속",
  link: "링크",
  content: "직접 추가",
  instagram: "인스타그램",
  youtube: "유튜브",
  facebook: "페이스북",
  x: "X",
  tiktok: "틱톡",
  naver: "네이버 블로그",
  linkedIn: "링크드인",
  notefolio: "노트폴리오",
  behance: "비핸스",
  github: "깃허브",
  kakao: "카카오톡",
};
