import {
  alphabetThumbnail,
  fieldThumbnail,
  numberThumbnail,
  emotionThumbnail,
  seasonThumbnail,
  field_1,
  field_2,
  field_3,
  field_4,
  field_5,
  field_6,
  field_7,
  field_8,
  field_9,
  field_10,
  field_11,
  field_12,
  field_13,
  field_14,
  field_15,
  field_16,
  yellow1,
  yellow2,
  yellow3,
  yellow4,
  yellow5,
  yellow6,
  yellow7,
  yellow8,
  yellow9,
  yellow0,
  red1,
  red2,
  red3,
  red4,
  red5,
  red6,
  red7,
  red8,
  red9,
  red0,
  green1,
  green2,
  green3,
  green4,
  green5,
  green6,
  green7,
  green8,
  green9,
  green0,
  blue1,
  blue2,
  blue3,
  blue4,
  blue5,
  blue6,
  blue7,
  blue8,
  blue9,
  blue0,
  black1,
  black2,
  black3,
  black4,
  black5,
  black6,
  black7,
  black8,
  black9,
  black0,
  yellowA,
  yellowB,
  yellowC,
  yellowD,
  yellowE,
  yellowF,
  yellowG,
  yellowH,
  yellowI,
  yellowJ,
  yellowK,
  yellowL,
  yellowM,
  yellowN,
  yellowO,
  yellowP,
  yellowQ,
  yellowR,
  yellowS,
  yellowT,
  yellowU,
  yellowV,
  yellowW,
  yellowX,
  yellowY,
  yellowZ,
  redA,
  redB,
  redC,
  redD,
  redE,
  redF,
  redG,
  redH,
  redI,
  redJ,
  redK,
  redL,
  redM,
  redN,
  redO,
  redP,
  redQ,
  redR,
  redS,
  redT,
  redU,
  redV,
  redW,
  redX,
  redY,
  redZ,
  greenA,
  greenB,
  greenC,
  greenD,
  greenE,
  greenF,
  greenG,
  greenH,
  greenI,
  greenJ,
  greenK,
  greenL,
  greenM,
  greenN,
  greenO,
  greenP,
  greenQ,
  greenR,
  greenS,
  greenT,
  greenU,
  greenV,
  greenW,
  greenX,
  greenY,
  greenZ,
  blueA,
  blueB,
  blueC,
  blueD,
  blueE,
  blueF,
  blueG,
  blueH,
  blueI,
  blueJ,
  blueK,
  blueL,
  blueM,
  blueN,
  blueO,
  blueP,
  blueQ,
  blueR,
  blueS,
  blueT,
  blueU,
  blueV,
  blueW,
  blueX,
  blueY,
  blueZ,
  blackA,
  blackB,
  blackC,
  blackD,
  blackE,
  blackF,
  blackG,
  blackH,
  blackI,
  blackJ,
  blackK,
  blackL,
  blackM,
  blackN,
  blackO,
  blackP,
  blackQ,
  blackR,
  blackS,
  blackT,
  blackU,
  blackV,
  blackW,
  blackX,
  blackY,
  blackZ,
  emotion_1,
  emotion_2,
  emotion_3,
  emotion_4,
  emotion_5,
  emotion_6,
  emotion_7,
  emotion_8,
  emotion_9,
  emotion_10,
  emotion_11,
  emotion_12,
  emotion_13,
  emotion_14,
  emotion_15,
  emotion_16,
  emotion_17,
  emotion_18,
  emotion_19,
  emotion_20,
  season_1,
  season_2,
  season_3,
  season_4,
  season_5,
  season_6,
  season_7,
  season_8,
  season_9,
  season_10,
  season_11,
  season_12,
  season_13,
  season_14,
  season_15,
  season_16,
  season_17,
  season_18,
  season_19,
  season_20,
} from "./importStickers";

export const stickerMapping = {
  field_1: field_1,
  field_2: field_2,
  field_3: field_3,
  field_4: field_4,
  field_5: field_5,
  field_6: field_6,
  field_7: field_7,
  field_8: field_8,
  field_9: field_9,
  field_10: field_10,
  field_11: field_11,
  field_12: field_12,
  field_13: field_13,
  field_14: field_14,
  field_15: field_15,
  field_16: field_16,
  yellow1: yellow1,
  yellow2: yellow2,
  yellow3: yellow3,
  yellow4: yellow4,
  yellow5: yellow5,
  yellow6: yellow6,
  yellow7: yellow7,
  yellow8: yellow8,
  yellow9: yellow9,
  yellow0: yellow0,
  red1: red1,
  red2: red2,
  red3: red3,
  red4: red4,
  red5: red5,
  red6: red6,
  red7: red7,
  red8: red8,
  red9: red9,
  red0: red0,
  green1: green1,
  green2: green2,
  green3: green3,
  green4: green4,
  green5: green5,
  green6: green6,
  green7: green7,
  green8: green8,
  green9: green9,
  green0: green0,
  blue1: blue1,
  blue2: blue2,
  blue3: blue3,
  blue4: blue4,
  blue5: blue5,
  blue6: blue6,
  blue7: blue7,
  blue8: blue8,
  blue9: blue9,
  blue0: blue0,
  black1: black1,
  black2: black2,
  black3: black3,
  black4: black4,
  black5: black5,
  black6: black6,
  black7: black7,
  black8: black8,
  black9: black9,
  black0: black0,
  yellowA: yellowA,
  yellowB: yellowB,
  yellowC: yellowC,
  yellowD: yellowD,
  yellowE: yellowE,
  yellowF: yellowF,
  yellowG: yellowG,
  yellowH: yellowH,
  yellowI: yellowI,
  yellowJ: yellowJ,
  yellowK: yellowK,
  yellowL: yellowL,
  yellowM: yellowM,
  yellowN: yellowN,
  yellowO: yellowO,
  yellowP: yellowP,
  yellowQ: yellowQ,
  yellowR: yellowR,
  yellowS: yellowS,
  yellowT: yellowT,
  yellowU: yellowU,
  yellowV: yellowV,
  yellowW: yellowW,
  yellowX: yellowX,
  yellowY: yellowY,
  yellowZ: yellowZ,
  redA: redA,
  redB: redB,
  redC: redC,
  redD: redD,
  redE: redE,
  redF: redF,
  redG: redG,
  redH: redH,
  redI: redI,
  redJ: redJ,
  redK: redK,
  redL: redL,
  redM: redM,
  redN: redN,
  redO: redO,
  redP: redP,
  redQ: redQ,
  redR: redR,
  redS: redS,
  redT: redT,
  redU: redU,
  redV: redV,
  redW: redW,
  redX: redX,
  redY: redY,
  redZ: redZ,
  greenA: greenA,
  greenB: greenB,
  greenC: greenC,
  greenD: greenD,
  greenE: greenE,
  greenF: greenF,
  greenG: greenG,
  greenH: greenH,
  greenI: greenI,
  greenJ: greenJ,
  greenK: greenK,
  greenL: greenL,
  greenM: greenM,
  greenN: greenN,
  greenO: greenO,
  greenP: greenP,
  greenQ: greenQ,
  greenR: greenR,
  greenS: greenS,
  greenT: greenT,
  greenU: greenU,
  greenV: greenV,
  greenW: greenW,
  greenX: greenX,
  greenY: greenY,
  greenZ: greenZ,
  blueA: blueA,
  blueB: blueB,
  blueC: blueC,
  blueD: blueD,
  blueE: blueE,
  blueF: blueF,
  blueG: blueG,
  blueH: blueH,
  blueI: blueI,
  blueJ: blueJ,
  blueK: blueK,
  blueL: blueL,
  blueM: blueM,
  blueN: blueN,
  blueO: blueO,
  blueP: blueP,
  blueQ: blueQ,
  blueR: blueR,
  blueS: blueS,
  blueT: blueT,
  blueU: blueU,
  blueV: blueV,
  blueW: blueW,
  blueX: blueX,
  blueY: blueY,
  blueZ: blueZ,
  blackA: blackA,
  blackB: blackB,
  blackC: blackC,
  blackD: blackD,
  blackE: blackE,
  blackF: blackF,
  blackG: blackG,
  blackH: blackH,
  blackI: blackI,
  blackJ: blackJ,
  blackK: blackK,
  blackL: blackL,
  blackM: blackM,
  blackN: blackN,
  blackO: blackO,
  blackP: blackP,
  blackQ: blackQ,
  blackR: blackR,
  blackS: blackS,
  blackT: blackT,
  blackU: blackU,
  blackV: blackV,
  blackW: blackW,
  blackX: blackX,
  blackY: blackY,
  blackZ: blackZ,
  emotion_1: emotion_1,
  emotion_2: emotion_2,
  emotion_3: emotion_3,
  emotion_4: emotion_4,
  emotion_5: emotion_5,
  emotion_6: emotion_6,
  emotion_7: emotion_7,
  emotion_8: emotion_8,
  emotion_9: emotion_9,
  emotion_10: emotion_10,
  emotion_11: emotion_11,
  emotion_12: emotion_12,
  emotion_13: emotion_13,
  emotion_14: emotion_14,
  emotion_15: emotion_15,
  emotion_16: emotion_16,
  emotion_17: emotion_17,
  emotion_18: emotion_18,
  emotion_19: emotion_19,
  emotion_20: emotion_20,
  season_1: season_1,
  season_2: season_2,
  season_3: season_3,
  season_4: season_4,
  season_5: season_5,
  season_6: season_6,
  season_7: season_7,
  season_8: season_8,
  season_9: season_9,
  season_10: season_10,
  season_11: season_11,
  season_12: season_12,
  season_13: season_13,
  season_14: season_14,
  season_15: season_15,
  season_16: season_16,
  season_17: season_17,
  season_18: season_18,
  season_19: season_19,
  season_20: season_20,
};

export const stickerCategories = [
  { id: "field", thumbnail: fieldThumbnail },
  { id: "number", thumbnail: numberThumbnail },
  { id: "alphabet", thumbnail: alphabetThumbnail },
  { id: "emotion", thumbnail: emotionThumbnail },
  { id: "season", thumbnail: seasonThumbnail },
];

export const stickers = {
  field: [
    { name: "field_1", src: field_1 },
    { name: "field_2", src: field_2 },
    { name: "field_3", src: field_3 },
    { name: "field_4", src: field_4 },
    { name: "field_5", src: field_5 },
    { name: "field_6", src: field_6 },
    { name: "field_7", src: field_7 },
    { name: "field_8", src: field_8 },
    { name: "field_9", src: field_9 },
    { name: "field_10", src: field_10 },
    { name: "field_11", src: field_11 },
    { name: "field_12", src: field_12 },
    { name: "field_13", src: field_13 },
    { name: "field_14", src: field_14 },
    { name: "field_15", src: field_15 },
    { name: "field_16", src: field_16 },
  ],

  number: [
    { name: "yellow1", src: yellow1 },
    { name: "yellow2", src: yellow2 },
    { name: "yellow3", src: yellow3 },
    { name: "yellow4", src: yellow4 },
    { name: "yellow5", src: yellow5 },
    { name: "yellow6", src: yellow6 },
    { name: "yellow7", src: yellow7 },
    { name: "yellow8", src: yellow8 },
    { name: "yellow9", src: yellow9 },
    { name: "yellow0", src: yellow0 },
    { name: "red1", src: red1 },
    { name: "red2", src: red2 },
    { name: "red3", src: red3 },
    { name: "red4", src: red4 },
    { name: "red5", src: red5 },
    { name: "red6", src: red6 },
    { name: "red7", src: red7 },
    { name: "red8", src: red8 },
    { name: "red9", src: red9 },
    { name: "red0", src: red0 },
    { name: "green1", src: green1 },
    { name: "green2", src: green2 },
    { name: "green3", src: green3 },
    { name: "green4", src: green4 },
    { name: "green5", src: green5 },
    { name: "green6", src: green6 },
    { name: "green7", src: green7 },
    { name: "green8", src: green8 },
    { name: "green9", src: green9 },
    { name: "green0", src: green0 },
    { name: "blue1", src: blue1 },
    { name: "blue2", src: blue2 },
    { name: "blue3", src: blue3 },
    { name: "blue4", src: blue4 },
    { name: "blue5", src: blue5 },
    { name: "blue6", src: blue6 },
    { name: "blue7", src: blue7 },
    { name: "blue8", src: blue8 },
    { name: "blue9", src: blue9 },
    { name: "blue0", src: blue0 },
    { name: "black1", src: black1 },
    { name: "black2", src: black2 },
    { name: "black3", src: black3 },
    { name: "black4", src: black4 },
    { name: "black5", src: black5 },
    { name: "black6", src: black6 },
    { name: "black7", src: black7 },
    { name: "black8", src: black8 },
    { name: "black9", src: black9 },
    { name: "black0", src: black0 },
  ],
  alphabet: [
    { name: "yellowA", src: yellowA },
    { name: "yellowB", src: yellowB },
    { name: "yellowC", src: yellowC },
    { name: "yellowD", src: yellowD },
    { name: "yellowE", src: yellowE },
    { name: "yellowF", src: yellowF },
    { name: "yellowG", src: yellowG },
    { name: "yellowH", src: yellowH },
    { name: "yellowI", src: yellowI },
    { name: "yellowJ", src: yellowJ },
    { name: "yellowK", src: yellowK },
    { name: "yellowL", src: yellowL },
    { name: "yellowM", src: yellowM },
    { name: "yellowN", src: yellowN },
    { name: "yellowO", src: yellowO },
    { name: "yellowP", src: yellowP },
    { name: "yellowQ", src: yellowQ },
    { name: "yellowR", src: yellowR },
    { name: "yellowS", src: yellowS },
    { name: "yellowT", src: yellowT },
    { name: "yellowU", src: yellowU },
    { name: "yellowV", src: yellowV },
    { name: "yellowW", src: yellowW },
    { name: "yellowX", src: yellowX },
    { name: "yellowY", src: yellowY },
    { name: "yellowZ", src: yellowZ },
    { name: "redA", src: redA },
    { name: "redB", src: redB },
    { name: "redC", src: redC },
    { name: "redD", src: redD },
    { name: "redE", src: redE },
    { name: "redF", src: redF },
    { name: "redG", src: redG },
    { name: "redH", src: redH },
    { name: "redI", src: redI },
    { name: "redJ", src: redJ },
    { name: "redK", src: redK },
    { name: "redL", src: redL },
    { name: "redM", src: redM },
    { name: "redN", src: redN },
    { name: "redO", src: redO },
    { name: "redP", src: redP },
    { name: "redQ", src: redQ },
    { name: "redR", src: redR },
    { name: "redS", src: redS },
    { name: "redT", src: redT },
    { name: "redU", src: redU },
    { name: "redV", src: redV },
    { name: "redW", src: redW },
    { name: "redX", src: redX },
    { name: "redY", src: redY },
    { name: "redZ", src: redZ },
    { name: "greenA", src: greenA },
    { name: "greenB", src: greenB },
    { name: "greenC", src: greenC },
    { name: "greenD", src: greenD },
    { name: "greenE", src: greenE },
    { name: "greenF", src: greenF },
    { name: "greenG", src: greenG },
    { name: "greenH", src: greenH },
    { name: "greenI", src: greenI },
    { name: "greenJ", src: greenJ },
    { name: "greenK", src: greenK },
    { name: "greenL", src: greenL },
    { name: "greenM", src: greenM },
    { name: "greenN", src: greenN },
    { name: "greenO", src: greenO },
    { name: "greenP", src: greenP },
    { name: "greenQ", src: greenQ },
    { name: "greenR", src: greenR },
    { name: "greenS", src: greenS },
    { name: "greenT", src: greenT },
    { name: "greenU", src: greenU },
    { name: "greenV", src: greenV },
    { name: "greenW", src: greenW },
    { name: "greenX", src: greenX },
    { name: "greenY", src: greenY },
    { name: "greenZ", src: greenZ },
    { name: "blueA", src: blueA },
    { name: "blueB", src: blueB },
    { name: "blueC", src: blueC },
    { name: "blueD", src: blueD },
    { name: "blueE", src: blueE },
    { name: "blueF", src: blueF },
    { name: "blueG", src: blueG },
    { name: "blueH", src: blueH },
    { name: "blueI", src: blueI },
    { name: "blueJ", src: blueJ },
    { name: "blueK", src: blueK },
    { name: "blueL", src: blueL },
    { name: "blueM", src: blueM },
    { name: "blueN", src: blueN },
    { name: "blueO", src: blueO },
    { name: "blueP", src: blueP },
    { name: "blueQ", src: blueQ },
    { name: "blueR", src: blueR },
    { name: "blueS", src: blueS },
    { name: "blueT", src: blueT },
    { name: "blueU", src: blueU },
    { name: "blueV", src: blueV },
    { name: "blueW", src: blueW },
    { name: "blueX", src: blueX },
    { name: "blueY", src: blueY },
    { name: "blueZ", src: blueZ },
    { name: "blackA", src: blackA },
    { name: "blackB", src: blackB },
    { name: "blackC", src: blackC },
    { name: "blackD", src: blackD },
    { name: "blackE", src: blackE },
    { name: "blackF", src: blackF },
    { name: "blackG", src: blackG },
    { name: "blackH", src: blackH },
    { name: "blackI", src: blackI },
    { name: "blackJ", src: blackJ },
    { name: "blackK", src: blackK },
    { name: "blackL", src: blackL },
    { name: "blackM", src: blackM },
    { name: "blackN", src: blackN },
    { name: "blackO", src: blackO },
    { name: "blackP", src: blackP },
    { name: "blackQ", src: blackQ },
    { name: "blackR", src: blackR },
    { name: "blackS", src: blackS },
    { name: "blackT", src: blackT },
    { name: "blackU", src: blackU },
    { name: "blackV", src: blackV },
    { name: "blackW", src: blackW },
    { name: "blackX", src: blackX },
    { name: "blackY", src: blackY },
    { name: "blackZ", src: blackZ },
  ],

  emotion: [
    { name: "emotion_1", src: emotion_1 },
    { name: "emotion_2", src: emotion_2 },
    { name: "emotion_3", src: emotion_3 },
    { name: "emotion_4", src: emotion_4 },
    { name: "emotion_5", src: emotion_5 },
    { name: "emotion_6", src: emotion_6 },
    { name: "emotion_7", src: emotion_7 },
    { name: "emotion_8", src: emotion_8 },
    { name: "emotion_9", src: emotion_9 },
    { name: "emotion_10", src: emotion_10 },
    { name: "emotion_11", src: emotion_11 },
    { name: "emotion_12", src: emotion_12 },
    { name: "emotion_13", src: emotion_13 },
    { name: "emotion_14", src: emotion_14 },
    { name: "emotion_15", src: emotion_15 },
    { name: "emotion_16", src: emotion_16 },
    { name: "emotion_17", src: emotion_17 },
    { name: "emotion_18", src: emotion_18 },
    { name: "emotion_19", src: emotion_19 },
    { name: "emotion_20", src: emotion_20 },
  ],
  season: [
    { name: "season_1", src: season_1 },
    { name: "season_2", src: season_2 },
    { name: "season_3", src: season_3 },
    { name: "season_4", src: season_4 },
    { name: "season_5", src: season_5 },
    { name: "season_6", src: season_6 },
    { name: "season_7", src: season_7 },
    { name: "season_8", src: season_8 },
    { name: "season_9", src: season_9 },
    { name: "season_10", src: season_10 },
    { name: "season_11", src: season_11 },
    { name: "season_12", src: season_12 },
    { name: "season_13", src: season_13 },
    { name: "season_14", src: season_14 },
    { name: "season_15", src: season_15 },
    { name: "season_16", src: season_16 },
    { name: "season_17", src: season_17 },
    { name: "season_18", src: season_18 },
    { name: "season_19", src: season_19 },
    { name: "season_20", src: season_20 },
  ],
};
